_wandb:
    value:
        cli_version: 0.24.0
        e:
            3as6t1qaht5n83kzn334zjggrt3nsf7q:
                codePath: /home/subash/Quantization/main.ipynb
                codePathLocal: main.ipynb
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "146509295616"
                        used: "92515254272"
                email: subash.sharma@islingtoncollege.edu.np
                executable: /home/subash/Quantization/.quanti/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-21b2283b-8280-a659-dce7-b11a869d1196
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-551d91fa-def6-06de-565d-329c38ce3f83
                host: gov-Intel-R-Core-TM-i7-14700F
                memory:
                    total: "100941467648"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/subash/Quantization/main.ipynb
                python: CPython 3.13.11
                root: /home/subash/Quantization
                startedAt: "2026-01-19T04:08:13.389502Z"
                writerId: 3as6t1qaht5n83kzn334zjggrt3nsf7q
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 2
                - 13
            "4": 3.13.11
            "5": 0.24.0
            "6": 4.57.3
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
